#!/usr/bin/env python3
"""Assemble vendor/oneplus/ktm-opluscamera from the ktm stock dump.

The package is generated output and is not version controlled -- its 171 MB
APK exceeds GitHub's 100 MB per-file limit -- so this generator is the source
of truth, the same way extract-files.py is for vendor/oneplus/ktm.
"""
import os, shutil, subprocess, sys

# Overridable so this is not pinned to one workspace.
#   STOCK_DUMP   the extracted ktm stock firmware
#   ANDROID_ROOT the AOSP tree root
STOCK = os.environ.get("STOCK_DUMP", os.path.expanduser("~/ktm-16.0.10"))
_ROOT = os.environ.get(
    "ANDROID_ROOT",
    os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")),
)
TREE = os.path.join(_ROOT, "vendor/oneplus/ktm-opluscamera")
PROP = os.path.join(TREE, "proprietary")
STAGED = os.path.join(TREE, "staged")

# (src under STOCK, dst under proprietary/, partition var)
FILES = [
    ("my_product/app/OplusCamera/OplusCamera.apk",
     "product/app/OplusCamera/OplusCamera.apk", "PRODUCT"),
    ("my_product/product_overlay/framework/com.oplus.camera.unit.sdk.jar",
     "product/framework/com.oplus.camera.unit.sdk.jar", "PRODUCT"),
    ("my_product/product_overlay/framework/com.oplus.camera.unit.sdk.adapter.jar",
     "product/framework/com.oplus.camera.unit.sdk.adapter.jar", "PRODUCT"),
    ("my_product/product_overlay/etc/permissions/com.oplus.camera.unit.sdk_product.xml",
     "product/etc/permissions/com.oplus.camera.unit.sdk_product.xml", "PRODUCT"),
    # Declares all 53 com.oplus.permission.safe.* names (package "oplus", a resource-only
    # APK). Without it com.oplus.permission.safe.CAMERA is undeclared and can never be
    # granted -- see AGENTS.md 21r. Path mirrors stock; if PackageManager turns out not to
    # scan system_ext/framework, move it to system_ext/priv-app.
    ("system_ext_x/framework/oplus-framework-res.apk",
     "system_ext/framework/oplus-framework-res.apk", "SYSTEM_EXT"),
]

def sh(*a):
    return subprocess.run(a, capture_output=True, text=True).stdout


def main():
    os.makedirs(PROP, exist_ok=True)
    os.makedirs(STAGED, exist_ok=True)

    copied = []
    for src, dst, part in FILES:
        s = os.path.join(STOCK, src)
        if not os.path.exists(s):
            print("MISSING FROM DUMP: " + src)
            continue
        d = os.path.join(PROP, dst)
        os.makedirs(os.path.dirname(d), exist_ok=True)
        if not (os.path.exists(d) and os.path.getsize(d) == os.path.getsize(s)):
            shutil.copy2(s, d)
        copied.append((dst, part))

    # --- odm/etc/camera assets present in stock but absent from ktm's blob list ---
    listed = set()
    pf = os.path.join(_ROOT, "device/oneplus/ktm/proprietary-files.txt")
    with open(pf) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            p = line.split(";")[0].split("|")[0].strip().lstrip("-")
            if p.startswith("odm/etc/camera/"):
                listed.add(p)

    stock_cam = []
    base = os.path.join(STOCK, "odm/etc/camera")
    for root, _, names in os.walk(base):
        for n in names:
            full = os.path.join(root, n)
            rel = os.path.relpath(full, STOCK)
            stock_cam.append(rel)

    missing = sorted(set(stock_cam) - listed)
    for rel in missing:
        d = os.path.join(PROP, rel)
        os.makedirs(os.path.dirname(d), exist_ok=True)
        src_f = os.path.join(STOCK, rel)
        if not (os.path.exists(d) and os.path.getsize(d) == os.path.getsize(src_f)):
            shutil.copy2(src_f, d)
        copied.append((rel, "ODM"))

    # --- staged-only: oplus-framework.jar (NOT wired into the build, see README) ---
    os.makedirs(os.path.join(STAGED, "system/framework"), exist_ok=True)
    shutil.copy2(os.path.join(STOCK, "system_x/system/framework/oplus-framework.jar"),
                 os.path.join(STAGED, "system/framework/oplus-framework.jar"))

    # ---------------- makefiles ----------------
    part_var = {"PRODUCT": "$(TARGET_COPY_OUT_PRODUCT)", "ODM": "$(TARGET_COPY_OUT_ODM)",
                "SYSTEM_EXT": "$(TARGET_COPY_OUT_SYSTEM_EXT)"}
    prefix = {"PRODUCT": "product/", "ODM": "odm/", "SYSTEM_EXT": "system_ext/"}
    lines = []
    for dst, part in copied:
        rel = dst[len(prefix[part]):]
        lines.append("    $(LOCAL_PATH)/proprietary/%s:%s/%s" % (dst, part_var[part], rel))

    odm_lines = [l for l, p in zip(lines, [p for _, p in copied]) if p == "ODM"]
    app_lines = [l for l, p in zip(lines, [p for _, p in copied]) if p != "ODM"]

    mk = """# Automatically generated by vendor/oneplus/ktm-opluscamera/mktree.py
# Source: OnePlus Ace 6 (ktm) CN stock, ColorOS 16.0.10
#
# Stock ships the camera app on /my_product, an OPlus-only partition that does
# not exist in an AOSP build. Everything from there is remapped to /product.

LOCAL_PATH := vendor/oneplus/ktm-opluscamera

# ---------------------------------------------------------------------------
# Always: the odm/etc/camera assets.
#
# 127 files stock ships and our blob list does not -- ML models, colour LUTs,
# tuning configs, calibration and an algorithm licence. These are consumed by
# the CamX-CHI pipeline, so they improve capture for EVERY camera app on the
# device, org.lineageos.aperture included. Nothing here depends on the OPlus
# camera app being installed.
# ---------------------------------------------------------------------------
PRODUCT_COPY_FILES += \\
%s

# ---------------------------------------------------------------------------
# Opt-in: the stock OPlus camera app itself.
#
# NOT ready to ship. It starts and builds its preview renderer (AGENTS.md 21l)
# but then dies on SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE, which is
# signature|privileged|role and cannot be granted to an app installed in
# /product/app. Turning this on before the priv-app packaging and the
# privapp-permissions allowlist exist just puts a crashing camera in the
# launcher.
#
# Enable with TARGET_SHIP_OPLUS_CAMERA_APP := true once 21o is resolved.
# ---------------------------------------------------------------------------
ifeq ($(TARGET_SHIP_OPLUS_CAMERA_APP),true)

PRODUCT_COPY_FILES += \\
%s

PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += \\
    product/app/OplusCamera/OplusCamera.apk \\
    product/framework/com.oplus.camera.unit.sdk.jar \\
    product/framework/com.oplus.camera.unit.sdk.adapter.jar \\
    system_ext/framework/oplus-framework-res.apk

endif
""" % (" \\\n".join(odm_lines), " \\\n".join(app_lines))

    with open(os.path.join(TREE, "ktm-opluscamera-vendor.mk"), "w") as fh:
        fh.write(mk)

    with open(os.path.join(TREE, "BoardConfigVendor.mk"), "w") as fh:
        fh.write("# vendor/oneplus/ktm-opluscamera\n"
                 "# No board-level configuration is required: every artifact in this\n"
                 "# package is a copied file, not a built module.\n")

    print("files copied: %d" % len(copied))
    print("  product: %d" % sum(1 for _, p in copied if p == "PRODUCT"))
    print("  odm/etc/camera (gap vs proprietary-files.txt): %d" % len(missing))
    print("tree size: " + sh("du", "-sh", TREE).split()[0])


if __name__ == "__main__":
    main()
